[types]
img = ".*\\.(jp.?g|png|gif|JP.?G)$"
video = ".*\\.(flv|mp4|mp.?g|avi|wmv|mkv|3gp|m4v|asf|webm)$"
doc = ".*\\.(pdf|chm|epub|djvu?|mobi|azw3|odf|ods|md|tex|txt|adoc)$"
audio = ".*\\.(mp3|m4a|flac|ogg)$"
conf = ".*\\.(conf|config|cfg)$"
code = ".*\\.(pl|rs|zsh|sh|bash|go|java|js|ts)"
shell = ".*\\.(pl|zsh|sh|bash)"
